version: "3.9"

services:
  db:
    build: ./db
    container_name: db
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "currency-db", "-U", "postgres" ]
      timeout: 5s #tempo da tentativa
      interval: 5s #intervalo entre elas
      retries: 3 #qtd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: currency-db
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
    networks:
      - rede

  api:
    build: .
    container_name: api
    image: currency-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/currency-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    ports:
      #cada requisicao feita na 8080 da maquina vai ser redirecionada para 8080 do container
      - "8080:8080"
    networks:
      - rede
  sonarqube:
    image: sonarqube:9.9.0-community
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/currency-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"


networks:
  rede: {}

volumes:
  postgres_data: {}
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
